name: Publish

on:
    workflow_call:
        inputs:
            commit:
                required: true
                type: string

jobs:
    pages:
        name: GitHub Page
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            pages: write
            id-token: write
        steps:
            - uses: actions/download-artifact@v4
              with:
                  name: idee_pwa_pages
                  path: ./page

            - uses: actions/upload-pages-artifact@v3
              with:
                  path: ./page

            - uses: actions/deploy-pages@v4
