name: Branch

on:
    push:
        branches-ignore:
            - 'main'

jobs:
    build:
        name: Build
        uses: ./.github/workflows/build.yml
        with:
            commit: github.event.inputs.sha
            signed: false
        secrets: inherit
